name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: false  # Ensure fresh install

    - name: Clean Old Dependencies
      run: |
        rm -rf vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Install Gems
      run: |
        gem install bundler
        bundle update --bundler
        bundle install --jobs 4 --retry 3
    - name: Install deps
      run: |
        npm install -g mermaid.cli
    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> "$GITHUB_ENV"
          echo "NO_PUSH=--no-push" >> "$GITHUB_ENV"
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> "$GITHUB_ENV"
    - name: Deploy website 
      run: |
        yes | bash bin/deploy --verbose $NO_PUSH \
                    --src $SRC_BRANCH \
                    --deploy $DEPLOY_BRANCH
